baseurl: 'https://kazandiran-market.com'
description: Türkiye'nin İlk ve Tek Prim Kazandıran Süpermarketi
email: your-email@example.com
facebook: https://www.facebook.com/kazandiranmarketim/
instagram: https://www.instagram.com/kazandiranmarketim/
pinterest: https://www.pinterest.com/kazandiranmarketim/
plugins:
- jekyll-feed
reflink: https://www.kazandiranmarketim.com/satis_temsilcisi/irfan-salgir-8629
slider:
- url: https://kazandiranmarketim.com/images/slider/1599491438_hafta.png
- url: https://kazandiranmarketim.com/images/slider/1599145326_site.png
- url: https://kazandiranmarketim.com/images/slider/1598595957_ok.png
- url: https://kazandiranmarketim.com/images/slider/1598556867_asurebanner.png
- url: https://kazandiranmarketim.com/images/slider/1597651648_bannernew.jpg
theme: minima
title: Kazandıran Marketim
url: 'https://kazandiran-market.com'
urunler: https://kazandiranmarketim.com/urunler
youtube: none
